# Generated by Django 4.0.5 on 2022-06-30 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('intensity', models.TextField(default='')),
                ('focus', models.TextField(default='')),
                ('Duration', models.TextField(default='')),
                ('planID', models.TextField(default='', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=40)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('age', models.TextField(default='')),
                ('add', models.TextField(default='')),
                ('contact', models.TextField(default='')),
                ('disease', models.TextField(default='')),
                ('specifydisease', models.TextField(default='')),
                ('plan', models.TextField(default='')),
                ('total', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('feedback', models.TextField(default='')),
                ('concern', models.TextField(default='')),
                ('complaints', models.TextField(default='')),
                ('reviewID', models.TextField(default='', primary_key=True, serialize=False)),
                ('review_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftsys.item')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('DietPlan', models.TextField(default='')),
                ('Trainer', models.TextField(default='')),
                ('Duration', models.TextField(default='')),
                ('programID', models.TextField(default='', primary_key=True, serialize=False)),
                ('prg_prd', models.ManyToManyField(to='ftsys.exerciseplan')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('focus', models.TextField(default='')),
                ('supplements', models.TextField(default='')),
                ('clothing', models.TextField(default='')),
                ('extras', models.TextField(default='')),
                ('productID', models.TextField(default='', primary_key=True, serialize=False)),
                ('program_product', models.ManyToManyField(to='ftsys.program')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseplan',
            name='customer_plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ftsys.item'),
        ),
    ]
